# Make the workers services list
{{- $labels := .Values.common.labels }}
{{- range $workers := .Values.workers }}
apiVersion: v1
kind: Service
metadata:
  name: app-service-{{ $workers }}
  labels:
    {{ $workers }}
    {{- range $key, $value := $labels }}
    {{ $value }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}