# Make the workers list

apiVersion: apps/v1
kind: Deployment
metadata:
  name: <NAME>
  labels:
spec:
  selector:
    matchLabels: <LABELS>
  template:
    metadata:
      labels: <LABELS>
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

